### ISSUE TITLE
Cannot find module './evaluation-context' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ramtinsoltani** [Flagsmith/flagsmith-js-client#283]
I'm trying to setup Flagsmith in my Angular project and I cannot get the project compiled after installing `flagsmith` package from NPM and initializing it like below after following the documentation:

```ts
import { Injectable } from '@angular/core';
import flagsmith from 'flagsmith';
import { IFlags, IRetrieveInfo, LoadingState } from 'flagsmith/types';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class FlagsmithService {

  constructor() { }

  public init(): void {

    flagsmith.init({
      environmentID: environment.FLAGSMITH_ENV_ID,
      api: environment.FLAGSMITH_API,
      cacheFlags: true,
      enableAnalytics: true,
      onChange: this.onChange.bind(this)
    });

  }

  private onChange(oldFlags: IFlags<string> | null, params: IRetrieveInfo, loadingState: LoadingState): void {

    // ...

  }

}
```

The error is:
```
Error: node_modules/flagsmith/types.d.ts:1:86 - error TS2307: Cannot find module './evaluation-context' or its corresponding type declarations.

1 import { EvaluationContext, IdentityEvaluationContext, TraitEvaluationContext } from "./evaluation-context";
```

I can't find `evaluation-context.ts` in the installed package, but I see it in this repository. This is the documentation I have followed: https://docs.flagsmith.com/clients/javascript

Any idea why I'm getting this error and why this file is missing from the NPM package? I have tried the latest version as well as v8.* to no avail.

I'm also a bit confused about the documentation as the NPM package has marked `environmentID` in `IInitConfig` interface deprecated (`@deprecated — Please consider using evaluationContext.identity: IInitConfig.evaluationContext.`) while I can't find anything in the documentation about this.

**Comment by matthewelwell** [comment]
Hi @ramtinsoltani , can you please confirm which version of the client you are using?

**Comment by tiagoapolo** [comment]
Fixed on https://github.com/Flagsmith/flagsmith-js-client/releases/tag/9.0.1

**Comment by ramtinsoltani** [comment]
@tiagoapolo @matthewelwell I just updated to the latest version 9.0.1 (was using 9.0.0 previously) and the problem is still there when running the application using `ng serve` or building it with `ng build --aot`:
```
Error: node_modules/flagsmith/types.d.ts:1:86 - error TS2307: Cannot find module './evaluation-context' or its corresponding type declarations.

1 import { EvaluationContext, IdentityEvaluationContext, TraitEvaluationContext } from "./evaluation-context";
```

I'm using `npm install flagsmith` (installed `"flagsmith": "^9.0.1",` in package.json) with Angular 18.2 and TypeScript 5.5.4

**Comment by kyle-ssg** [comment]
Hi @ramtinsoltani although I cannot replicate this in an angular project, I can see why it would occur. Also you are correct to question the evaluation context - we've un-deprecated its predecessors whilst we document it further.

If you're able, could you confirm that flagsmith@9.0.2-beta.1 resolves your issue? 

Thanks

**Comment by ramtinsoltani** [comment]
@kyle-ssg Thank you for your response. I just tried flagsmith@9.0.2-beta.1 and the Angular build went through successfully.

**Comment by kyle-ssg** [comment]
@ramtinsoltani This is now released in flagsmith@9.0.2, thanks for raising!
